### ISSUE TITLE
Parameters shouldn't be stored as JSON objects

### ISSUE THREAD

**Issue by dunglas** [httpwg/structured-field-tests#48]
By the SFV spec, parameters are ordered:

> Parameters are an ordered map of key-value pairs that are associated with an Item (Section 3.3) or Inner List (Section 3.1.1).

However, by the JSON spec, JSON objects aren't ordered:

> An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number,  boolean, null, object, or array.

Several JSON parsers (including the JSON parser included in the standard library of Go: https://github.com/golang/go/issues/27179) aren't able to preserve the order, and make the test suite hard to use. An array of arrays (or of objects) should be used instead.

**Comment by mnot** [comment]
Makes sense. I think this needs conversion via a script...
