### ISSUE TITLE
test cases for sf-date

### ISSUE THREAD

**Issue by reschke** [httpwg/structured-field-tests#82]
We need a way to test parsers that support sf-date.

How to do that depends a bit on how the "migration" to the new, extended format is to happen. Do we just expect everybody to adopt the new format "automatically", or will this be a conscious decision by the party invoking the parser?

**Comment by pinicarus** [comment]
Hello,

I don't see references to a `sf-date` type in https://httpwg.org/specs/rfc8941.html.

Is it a type that will be added in a future draft but absent from draft 17?
If so, is there any planned date for this change or an online version of the work in progress?

Thanks for your feedback

**Comment by reschke** [comment]
See https://github.com/httpwg/http-extensions/issues/2393
